application: gasolinaland
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: gasolinaland.app

libraries:
- name: jinja2
  version: latest
